### ISSUE TITLE
GitHub Actions Testing and DockerFile Changes

### ISSUE THREAD

**Issue by karkir0003** [DSGT-DLP/dlp-cli#2]
this PR is a follow-up PR to https://github.com/DSGT-DLP/dlp-cli/pull/1

Please understand the above PR fully, before moving onto this one.

in order to flesh out the above PR we need to do the following:

GitHub Action Integration: Implement GitHub Action that automatically checks if the changes we made to Go files work seamlessly within the Cobra framework, ensuring our CLI commands are reliable. Consult the .yaml workflows for this.

Efficient Production Deployment: Create a mechanism to delete the .env file before deploying to the production environment and then automatically recreate it during container assignment on EC2 instances. This guarantees that our production environment always has the latest configurations. You can edit the Dockerfile for this. 

**TO-DO LIST**

- [ ] - Implement Github Action that runs on PR to see if the modified/added go files work properly in Cobra framework
- [ ] -  Implement a mechanism to delete the .env file before deploying to production and recreate it during container assignment on EC2 instances.
- [ ] -  Configure CLI command to pull the production configs and regenerate the .env file during container assignment.

**Comment by codingwithsurya** [comment]
@karkir0003 follow up pr to centralize envs

**Comment by codingwithsurya** [comment]
eta: thinking thursday pair prog, may need more time though

**Comment by karkir0003** [comment]
@codingwithsurya added this to the project board under in progress
